### ISSUE TITLE
Limit by country

### ISSUE THREAD

**Issue by jonataswalker** [rCarto/photon#1]
Hi there,

I'm not sure if this is the right place but I wrote a small [geocoder plugin](https://github.com/jonataswalker/ol3-geocoder) to OpenLayers 3 and would like to know about limiting the search by country. I don't see anything about this feature in [main page](http://photon.komoot.de/).

Best regards.

**Comment by rCarto** [comment]
Hi,
I am just the author of a R plugin (package) that uses photon. I guess the best place to ask would be on the photon github https://github.com/komoot/photon/issues
Best regards,
 Tim

**Comment by jonataswalker** [comment]
All right, thank you.
