### ISSUE TITLE
Unable to find an inherited method for function ‘fromJSON’

### ISSUE THREAD

**Issue by ghost** [rCarto/photon#10]
Hi, 

I am new to photon and  getting this error:

0Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘fromJSON’ for signature ‘"NULL", "missing"

I am getting this error by using the geocode example. 

address <- c("19 rue Michel Bakounine, 29600 Morlaix, France",
             "5 rue Proudhon, 34130 Mauguio France",
             "2 Emma Goldmanweg, Tilburg, Netherlands",
             "36 Strada Panait Israti, Bucarest, Romania")
place <- geocode(address, limit = 1, key = "place")
place

Thank you,
Alex

**Comment by justin-olson** [comment]
Hi, 

I am having the same error with large batches of geocoding. Although I wasn't able to reproduce your example. Did you happen to figure out what was producing the error?

**Comment by rCarto** [comment]
Hi, 
It could be due to a problem with the demo photon server. For large batches you should use your own instance of photon (see https://github.com/komoot/photon#installation)
