### ISSUE TITLE
Arguments are not allowed for R version 3.6.1

### ISSUE THREAD

**Issue by JoyceMbiguidi** [rCarto/photon#11]
loc <- geocode(df$address, limit = 1, key = "place")

Error in geocode(df$address, limit = 1, key = "place") : 
  unused arguments (limit = 1, key = "place")

R_version
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes

**Comment by rCarto** [comment]
Hi, 
Can you provide a reproducible example (https://www.tidyverse.org/help/) ?
