### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by JoyceMbiguidi** [rCarto/photon#12]
Sometimes {photon} does not work properly. I have the following error : 
Error: $ operator is invalid for atomic vectors.

df1 <- photon::geocode(df2$address, limit = 1, key = "place")

df2 is tbl_df() or data.frame() and nrow(df2) = 7006.
However, another day this script can work fine with nrow(df2) = 18000.

R version : 
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes

**Comment by rCarto** [comment]
Hi,
Can you provide a reproducible example (https://www.tidyverse.org/help/) ?

**Comment by mattischneider** [comment]
I just got the same error:

```
library(photon)
photon::geocode("Southern & Eastern Serbia")
```
returns `Error: $ operator is invalid for atomic vectors`.

the problem seems to be the `&` in the text:
`photon::geocode("Southern and Eastern Serbia")` works without errors

```
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] photon_1.1      forcats_0.4.0   stringr_1.4.0   dplyr_0.8.4     purrr_0.3.3     readr_1.3.1    
 [7] tidyr_1.0.2     tibble_2.1.3    ggplot2_3.2.1   tidyverse_1.3.0```

**Comment by rCarto** [comment]
Hum, that does not surprise me. "&" is used as input separator in the photon API. 
My solution would be to get rid of these special symbols (&, $, ?...) in the searched strings before using `photon::geocode()`.
