### ISSUE TITLE
Update to the API address

### ISSUE THREAD

**Issue by datapumpernickel** [rCarto/photon#15]
Hi,

thanks for this wonderfully convenient package! 
I noticed, that as of soon it might stop working, or already did so, because of a change in the API of photon. 
Specifically, the default server needs to be changed to: "https://photon.komoot.io/".

Thanks again and all the best!

#16

**Comment by rCarto** [comment]
See 5ac5089cae3a5877e6e8d943b298f332d86473dc and my comments under #16
