### ISSUE TITLE
Results for NYC are completely off

### ISSUE THREAD

**Issue by asitemade4u** [rCarto/photon#18]
Hi,

And thank you for the R plugin.

However, I have severe issues with the accuracy of the geocoding.
Here is the detail:

1. I have installed the last version of Photon server on our server, with the latest data, yesterday
2. I have several addresses in NYC I want to check and geocode. They are saved as an R dataframe under this form, which is the standardized address form in the US:

```text
1000 Richmond Terrace, New York, NY 10301 United States
75 Ninth Avenue, New York, NY 10011 United States
536 West 112th Street, New York, NY 10025 United States
90 West Houston Street, New York, NY 10012 United States
1008 Manhattan Ave, New York, NY 11222 United States
1700 Second Ave, New York, NY 10128 United States
52 Prince Street, New York, NY 10012 United States
225 Madison Avenue, New York, NY 10016 United States
147 Greene Avenue, New York, NY 11238 United States
228 West 47th Street, New York, NY 10036 United States
579 5th avenue, New York, NY 11215 United States
116 East 59th Street, New York, NY 10022 United States
162 Fifth Avenue, New York, NY 11217 United States
173 7th Ave. South, New York, NY 10014 United States
```

They are all valid addresses, coming from a local government agency.

3. The addresses belong to a dataframe, `plctst`, in the `ads` column. Then I geocode them using my server, thus:

```R
adsnrm <- photon::geocode(plctst$ads, limit = 1, server = <my-server-url>, lang = "en", key = "building")
```

4. The results are completely off.
I attach the `csv` file for the 50 first random addresses: [geocode_5_tst.csv](https://github.com/rCarto/photon/files/12882575/geocode_5_tst.csv)

While I can understand the results for some of the addresses, which are obviously malformed (e.g. row 3), I cannot understand why simple addresses yield results so wrong...

Of course, I have tried:

- using different `key` parameters: `place`, no key > the same
- removing the `lang` parameter altogether > the same
- removing the postal code within the address > the same
- changing the order of the components in each address, such as described in #5 > same result

And I am not sure the errors belong to the plugin or to the server.

Please let me know what I am doing wrong.
Thanks,
S.

P.S. Je suis français, vivant aux US. Si vous souhaitez continuer en français, dites-moi.

**Comment by asitemade4u** [comment]
As a complement, I have tried to geolocate most of the wrong results in Photon, using the exact same address shape, in the [online Nominatim](https://nominatim.openstreetmap.org/ui/search.html) and the results where correct.

**Comment by rCarto** [comment]
Hello @asitemade4u, 
Unfortunately I do not actively maintain (or use) this package anymore. I would advise to use [`tidygeocoder`](https://jessecambon.github.io/tidygeocoder/)  instead.
