### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by jjclegg** [rCarto/photon#3]
I can't get this to work on Rstudio Version 0.99.902
I run the code and the package successfully installs but it fails to create a geocode function.

**Comment by rCarto** [comment]
What message do you get? 
Does the following script work ? 

``` r
library(photon)
loc <- c("19 rue Michel Bakounine, 29600 Morlaix, France",
         "5 rue Proudhon, 34130 Mauguio, France",
         "2 Emma Goldmanweg, Tilburg, Netherlands",
         "36 Strada Panait Israti, Bucarest, Romania")
geocode(loc, limit = 1, key = "place")
```

**Comment by jjclegg** [comment]
The message I get is no geocode function found.

Here's my code:

require(devtools)  
devtools::install_github(repo = 'rCarto/photon') 
geocode("36 Strada Panait Israti, Bucarest, Romania", limit = 1, key = "place")

**Comment by rCarto** [comment]
I see, you have forgotten to load the package before the function call, you should write : 

``` r
library(photon)
geocode("36 Strada Panait Israti, Bucarest, Romania", limit = 1, key = "place")
```

**Comment by jjclegg** [comment]
Thank you!
