### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by wilcar** [rCarto/photon#4]
Hello, Using this script: 

      loc <- c("19 rue Michel Bakounine, 29600 Morlaix, France",
         "5 rue Proudhon, 34000 Montpellier, France",
         "2 Emma Goldmanweg, Tilburg, Netherlands",
         "36 Strada Panait Israti, Bucarest, Romania")
      geocode(loc, limit = 1, key = "place")

give me this error:

       Error in (function (classes, fdef, mtable)  : 
       unable to find an inherited method for function ‘fromJSON’ for signature ‘"NULL", "missing"’

**Comment by rCarto** [comment]
I don't see that error on my computer... Could have been a problem on photon server...
