### ISSUE TITLE
Activate German language

### ISSUE THREAD

**Issue by Toniiiio** [rCarto/photon#9]
In the docu it is written, that German, French, Italian are supported: https://github.com/komoot/photon.

How can i activate German language support, so that `geocode("Türkei", Limit = 1) ` does give the coordinates of Turkey.

Thank you!

**Comment by rCarto** [comment]
Hello, 
You have to use the `lang` parameter:
``` r
library(photon)
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.4.0, PROJ 5.2.0
library(cartography)
p <- geocode("Türkei", limit = 1, lang = "de")
p_sf = st_as_sf(p, coords = c("lon", "lat"), crs = 4326)

osm <- getTiles(x = st_buffer(p_sf,3), zoom=6,verbose = F)
#> Warning in st_buffer.sfc(st_geometry(x), dist, nQuadSegs, endCapStyle =
#> endCapStyle, : st_buffer does not correctly buffer longitude/latitude data
#> dist is assumed to be in decimal degrees (arc_degrees).
par(mar=c(0,0,0,0))
tilesLayer(osm)
plot(st_geometry(p_sf), add=T, pch=20, col = "red")
```

![](https://i.imgur.com/bYZHOPi.png)

<sup>Created on 2019-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
